### ISSUE TITLE
`go get -d` returns an error message

### ISSUE THREAD

**Issue by greg-szabo** [tendermint/trackomatron#23]
`go get -d` should download the source to the GPATH directory structure without errors. This is necessary for automation purposes. The files need to be under GOPATH but we build them manually using `make`.

I tried `git clone` but unless it's in the right folder structure, it's going to give error messages.

**Comment by adrianbrink** [comment]
How about `git cloning` into the correct folder structure? Even though that feels hacky.

**Comment by greg-szabo** [comment]
Exactly. Hacky. :) All other packages work fine, only this one and the new gaia package has this issue. (I guess because some files must be missing. Maybe the `cmd` folder? I didn't check yet.) I think a proper build process should be part of our development guidelines. Especially since we want to give this to third-party developers too.

**Comment by rigelrozanski** [comment]
another hacky solution if you need no errors `go get -d github.com/tendermint/trackomatron 2>/dev/null`

**Comment by rigelrozanski** [comment]
Okay so the original error was:
```
can't load package: package github.com/tendermint/trackomatron: no buildable Go source files in /home/riger/go2/src/github.com/tendermint/trackomatron
```
This makes sense are there are no buildable packages within the root dir of this folder... 
So instead either of these commands can be used (which generate no errors on my machine locally) 
`go get -d github.com/tendermint/trackomatron/...` 
`go get -d github.com/tendermint/trackomatron/cmd/...`
Please reopen this issue if there is a problem with my solution, but closing this issue for now

**Comment by greg-szabo** [comment]
Awesome solution rige, thanks. I'm using 

`go get -d github.com/tendermint/trackomatron/cmd/tracko`
