### ISSUE TITLE
make all ERROR

### ISSUE THREAD

**Issue by ghost** [tendermint/trackomatron#25]
test/cli.sh: line 187: jq: command not found
ERROR: No data returned for query
ASSERT:expected:<Invoices should have two entries> but was:<2>
test/cli.sh: line 191: jq: command not found
ERROR: No data returned for query
(standard_in) 1: parse error

stopping tracko test server...
Ran 6 tests.

FAILED (failures=51)
make: *** [test_cli] Error 1
jMac:trackomatron admin$

**Comment by rigelrozanski** [comment]
jq is a prerequisite to running the CLI tests, that is why this test is failing... `jq` is used to parse CLI output which comes in json. On Linux `jq` can be installed with `sudo apt-get install jq`

**Comment by rigelrozanski** [comment]
https://stedolan.github.io/jq/download/

**Comment by ghost** [comment]
thanks @rigelrozanski , and another i like ur hair
